/* tslint:disable */

/**
 ******************************************************************************
 * DO NOT MANUALLY EDIT THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED.
 ******************************************************************************
 */

import {NgModule} from '@angular/core';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {CommonModule} from '@angular/common';
import {MaterialModule} from './common/material-module';

import {PaginatorConfigurableExample} from './paginator/paginator-configurable/paginator-configurable-example';
import {PaginatorDemoExample} from './paginator/paginator-demo/paginator-demo-example';
import {PaginatorOverviewExample} from './paginator/paginator-overview/paginator-overview-example';

export interface LiveExample {
  title: string;
  component: any;
  additionalFiles?: string[];
  selectorName?: string;
}

export const EXAMPLE_COMPONENTS: {[key: string]: LiveExample} = {
  "paginator-configurable": {
    "title": "Configurable paginator",
    "component": PaginatorConfigurableExample,
    "additionalFiles": [],
    "selectorName": ""
  },
  "paginator-demo": {
    "title": "More Configurable paginator",
    "component": PaginatorDemoExample,
    "additionalFiles": [],
    "selectorName": ""
  },
  "paginator-overview": {
    "title": "Paginator",
    "component": PaginatorOverviewExample,
    "additionalFiles": [],
    "selectorName": ""
  }
};

export const EXAMPLE_LIST = [
  PaginatorConfigurableExample,
  PaginatorDemoExample,
  PaginatorOverviewExample
];

@NgModule({
  declarations: EXAMPLE_LIST,
  entryComponents: EXAMPLE_LIST,
  imports: [
    MaterialModule,
    FormsModule,
    ReactiveFormsModule,
    CommonModule
  ]
})
export class ExampleModule { }
